### ISSUE TITLE
Error when call php artisan connexion:install

### ISSUE THREAD

**Issue by dukenst2006** [bishopm/connexion#2]
Hello Bisho,
Congratulations for your app, Great job! I got some errors trying to install Connexion:
When I type php artisan connexion:install
It's gave me this error, how can i solve it, i want to test you app.
Any idea ?
 ` [ErrorException]`
 ` Undefined index: church_email`
Can you share with me the .sql file with me to test the app?
Keep on the good work !!
Cheer :)

**Comment by bishopm** [comment]
That error relates to a setting that should have been inserted when the install script was running (So in the settings table in your database, you need something like:

``` INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `description`, `category`, `created_at`, `updated_at`) VALUES (NULL, 'church_email', 'church@gmail.com', 'Church email address', 'General', NULL, NULL); ```

I tried to set up this package for a friend the other day and it took me a couple of hours because a lot of these initial setup things were broken - it comes from my having made manual DB changes during development and not updated the install script each time.

You can either keep plugging away or hang on till later in the month when Laravel 5.5 is released and I'll go through that whole install script and make sure that it is working.

Thanks for your interest :)

**Comment by dukenst2006** [comment]
Thanks @bishopm , I will try again with the installation. Keep on the good work !!

**Comment by mtb2450** [comment]
Hey Michael thanks for making this great project available!  Looking forward to the above fix.

Late note:

I manually created the settings table which got me by the above error; however, there are no other tables in the DB leaving artisan to now complaining about missing index "site_name".  The issue has left artisan broke, even a simple "php artisan list" fails with the missing site_name.

**Comment by dukenst2006** [comment]
Hello @bishopm 
You have anouced that you through that whole install script and make sure that it is working when the Laravel 5.5 is released, any news about this update.
Thanks for this great work.
Best regards

**Comment by bishopm** [comment]
I have updated this for L5.5 and resolved a number of the issues we were seeing earlier. There may still be some problems as I'm constantly updating the code, but you're welcome to try again :)

**Comment by dukenst2006** [comment]
Hello @bishopm 
thank you for your response, i try to install it again now it's give me this issue  `[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "connexion" namespace.`
when i make `php artisan connexion:install`
Thanks

**Comment by bishopm** [comment]
You still need to manually add the package service provider to config/app.php because Laravel's auto-discovery feature causes issues with some of the routes and I haven't managed to work around that yet.
I've updated the readme. 

Just ran a clean install and it seems to work fine, although at the moment you will still see content relating to my church - in time, themes will be customisable. At the moment this package is is daily use but only in one site that I'm aware of (so there is quite a bit of work to be done to remove all the hardcoded stuff that relates to that one site!) and I'm just fixing the bugs as they come up.

**Comment by mtb2450** [comment]
Thanks Michael for the update!  Nice, clean install.
